(display 1 2)
(display newline)
(define a 20)
(display a)
(define b a)
(display newline b "\n" newline)
(display (+ 1 (+ 100 120) 3) newline)
(define (add2 n) (+ n 3) (+ n 4) (+ n 2))
(display "hello, world" newline)
(display (add2 2) newline)
(define (fib n) (cond ((<= n 2) 1)
					  (else (+ (fib (- n 1)) (fib (- n 2))))))
(display (if false true false) newline)
(display (= 3 (add2 1)) newline)
(display (fib 10) newline)
(define (abc a b c) (+ a b c))
(display abc)
(define abc (abc 1))
(display abc)
(display (abc 2 3) newline)
(display (< 1 2) (<= 1 1) (> 1 2) (>= 2 2) newline)

(define sum (lambda (a b) (+ a b)))
(display (sum 10 20))
